package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomEntityImpl;
import cn.com.cscec8b.framework.model.common.CustomViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 29 09:10:38 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrVerifyHeaderTVORowImpl extends CustomViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CntrId {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrId();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrId((Number)value);
            }
        }
        ,
        CntrNumber {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrNumber();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrNumber((String)value);
            }
        }
        ,
        VerifyStartDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getVerifyStartDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setVerifyStartDate((Date)value);
            }
        }
        ,
        Status {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        VerifyEndDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getVerifyEndDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setVerifyEndDate((Date)value);
            }
        }
        ,
        DocumentNumber {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getDocumentNumber();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setDocumentNumber((String)value);
            }
        }
        ,
        CntrName {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrName();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrName((String)value);
            }
        }
        ,
        CustomerId {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        CustomerName {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        CustomerNumber {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCustomerNumber();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCustomerNumber((String)value);
            }
        }
        ,
        ProjectNumber {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getProjectNumber();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setProjectNumber((String)value);
            }
        }
        ,
        ProjectName {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getProjectName();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setProjectName((String)value);
            }
        }
        ,
        CntrConfirmDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrConfirmDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrConfirmDate((Date)value);
            }
        }
        ,
        ActualConfirmDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getActualConfirmDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setActualConfirmDate((Date)value);
            }
        }
        ,
        OwnerMeasureDelayTime {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getOwnerMeasureDelayTime();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setOwnerMeasureDelayTime((Number)value);
            }
        }
        ,
        CntrPaymentDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrPaymentDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrPaymentDate((Date)value);
            }
        }
        ,
        ActualPaymentDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getActualPaymentDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setActualPaymentDate((Date)value);
            }
        }
        ,
        OwnerPaymentDelayTime {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getOwnerPaymentDelayTime();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setOwnerPaymentDelayTime((Number)value);
            }
        }
        ,
        ActualOutput {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getActualOutput();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setActualOutput((Number)value);
            }
        }
        ,
        ActualPaymentAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getActualPaymentAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setActualPaymentAmount((Number)value);
            }
        }
        ,
        AlreadyConfirmAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAlreadyConfirmAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAlreadyConfirmAmount((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        CntrPaymentAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrPaymentAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrPaymentAmount((Number)value);
            }
        }
        ,
        CntrVerifyHeaderId {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrVerifyHeaderId();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrVerifyHeaderId((Number)value);
            }
        }
        ,
        CntrVisaConfirmQuantity {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCntrVisaConfirmQuantity();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCntrVisaConfirmQuantity((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LaborAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getLaborAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setLaborAmount((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ,
        OtherSubcntrOutput {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getOtherSubcntrOutput();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setOtherSubcntrOutput((Number)value);
            }
        }
        ,
        OwerConfirmQuantity {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getOwerConfirmQuantity();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setOwerConfirmQuantity((Number)value);
            }
        }
        ,
        PreparedBy {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getPreparedBy();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setPreparedBy((Number)value);
            }
        }
        ,
        PreparedByName {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getPreparedByName();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setPreparedByName((String)value);
            }
        }
        ,
        PreparedDate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getPreparedDate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setPreparedDate((Date)value);
            }
        }
        ,
        ProSubcntrOutput {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getProSubcntrOutput();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setProSubcntrOutput((Number)value);
            }
        }
        ,
        ProjectId {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setProjectId((Number)value);
            }
        }
        ,
        SecurityAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getSecurityAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setSecurityAmount((Number)value);
            }
        }
        ,
        CumulativeWithholdAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCumulativeWithholdAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCumulativeWithholdAmount((Number)value);
            }
        }
        ,
        CumulativeActualOutput {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCumulativeActualOutput();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCumulativeActualOutput((Number)value);
            }
        }
        ,
        TaxRate {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getTaxRate();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setTaxRate((String)value);
            }
        }
        ,
        MajorAmountTj {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getMajorAmountTj();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setMajorAmountTj((Number)value);
            }
        }
        ,
        MajorAmountAz {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getMajorAmountAz();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setMajorAmountAz((Number)value);
            }
        }
        ,
        MajorAmountZs {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getMajorAmountZs();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setMajorAmountZs((Number)value);
            }
        }
        ,
        MajorAmountGjg {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getMajorAmountGjg();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setMajorAmountGjg((Number)value);
            }
        }
        ,
        MajorAmountZnh {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getMajorAmountZnh();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setMajorAmountZnh((Number)value);
            }
        }
        ,
        MajorAmountOthers {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getMajorAmountOthers();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setMajorAmountOthers((Number)value);
            }
        }
        ,
        LeftConfirmAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getLeftConfirmAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setLeftConfirmAmount((Number)value);
            }
        }
        ,
        CurrentOwnerConfirmQuantities {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentOwnerConfirmQuantities();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentOwnerConfirmQuantities((Number)value);
            }
        }
        ,
        CurrentOtherSubCntrOutput {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentOtherSubCntrOutput();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentOtherSubCntrOutput((Number)value);
            }
        }
        ,
        CurrentActualOutput {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentActualOutput();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentActualOutput((Number)value);
            }
        }
        ,
        CurrentProSubcntrOutput {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentProSubcntrOutput();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentProSubcntrOutput((Number)value);
            }
        }
        ,
        CurrentLaborAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentLaborAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentLaborAmount((Number)value);
            }
        }
        ,
        CurrentCntrPaymentAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentCntrPaymentAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentCntrPaymentAmount((Number)value);
            }
        }
        ,
        CurrentSecurityAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentSecurityAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentSecurityAmount((Number)value);
            }
        }
        ,
        CurrentActualPaymentAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentActualPaymentAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentActualPaymentAmount((Number)value);
            }
        }
        ,
        CurrentLeftConfirmAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentLeftConfirmAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentLeftConfirmAmount((Number)value);
            }
        }
        ,
        CurrentAlreadyConfirmAmount {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentAlreadyConfirmAmount();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentAlreadyConfirmAmount((Number)value);
            }
        }
        ,
        CurrentVisaConfirmQuantity {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getCurrentVisaConfirmQuantity();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setCurrentVisaConfirmQuantity((Number)value);
            }
        }
        ,
        ConfirmValue {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getConfirmValue();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setConfirmValue((Number)value);
            }
        }
        ,
        BmCntrVerifyLineT {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getBmCntrVerifyLineT();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StatusLookupLovVO1 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getStatusLookupLovVO1();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmContractHeadersLovVO1 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getStmContractHeadersLovVO1();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmCustomersAndSitsLovVO1 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getStmCustomersAndSitsLovVO1();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmConfirmedCntrLovVO1 {
            public Object get(BmCntrVerifyHeaderTVORowImpl obj) {
                return obj.getStmConfirmedCntrLovVO1();
            }

            public void put(BmCntrVerifyHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BmCntrVerifyHeaderTVORowImpl object);

        public abstract void put(BmCntrVerifyHeaderTVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CNTRID = AttributesEnum.CntrId.index();
    public static final int CNTRNUMBER = AttributesEnum.CntrNumber.index();
    public static final int VERIFYSTARTDATE = AttributesEnum.VerifyStartDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int VERIFYENDDATE = AttributesEnum.VerifyEndDate.index();
    public static final int DOCUMENTNUMBER = AttributesEnum.DocumentNumber.index();
    public static final int CNTRNAME = AttributesEnum.CntrName.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CUSTOMERNUMBER = AttributesEnum.CustomerNumber.index();
    public static final int PROJECTNUMBER = AttributesEnum.ProjectNumber.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int CNTRCONFIRMDATE = AttributesEnum.CntrConfirmDate.index();
    public static final int ACTUALCONFIRMDATE = AttributesEnum.ActualConfirmDate.index();
    public static final int OWNERMEASUREDELAYTIME = AttributesEnum.OwnerMeasureDelayTime.index();
    public static final int CNTRPAYMENTDATE = AttributesEnum.CntrPaymentDate.index();
    public static final int ACTUALPAYMENTDATE = AttributesEnum.ActualPaymentDate.index();
    public static final int OWNERPAYMENTDELAYTIME = AttributesEnum.OwnerPaymentDelayTime.index();
    public static final int ACTUALOUTPUT = AttributesEnum.ActualOutput.index();
    public static final int ACTUALPAYMENTAMOUNT = AttributesEnum.ActualPaymentAmount.index();
    public static final int ALREADYCONFIRMAMOUNT = AttributesEnum.AlreadyConfirmAmount.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int CNTRPAYMENTAMOUNT = AttributesEnum.CntrPaymentAmount.index();
    public static final int CNTRVERIFYHEADERID = AttributesEnum.CntrVerifyHeaderId.index();
    public static final int CNTRVISACONFIRMQUANTITY = AttributesEnum.CntrVisaConfirmQuantity.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LABORAMOUNT = AttributesEnum.LaborAmount.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int OTHERSUBCNTROUTPUT = AttributesEnum.OtherSubcntrOutput.index();
    public static final int OWERCONFIRMQUANTITY = AttributesEnum.OwerConfirmQuantity.index();
    public static final int PREPAREDBY = AttributesEnum.PreparedBy.index();
    public static final int PREPAREDBYNAME = AttributesEnum.PreparedByName.index();
    public static final int PREPAREDDATE = AttributesEnum.PreparedDate.index();
    public static final int PROSUBCNTROUTPUT = AttributesEnum.ProSubcntrOutput.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int SECURITYAMOUNT = AttributesEnum.SecurityAmount.index();
    public static final int CUMULATIVEWITHHOLDAMOUNT = AttributesEnum.CumulativeWithholdAmount.index();
    public static final int CUMULATIVEACTUALOUTPUT = AttributesEnum.CumulativeActualOutput.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int MAJORAMOUNTTJ = AttributesEnum.MajorAmountTj.index();
    public static final int MAJORAMOUNTAZ = AttributesEnum.MajorAmountAz.index();
    public static final int MAJORAMOUNTZS = AttributesEnum.MajorAmountZs.index();
    public static final int MAJORAMOUNTGJG = AttributesEnum.MajorAmountGjg.index();
    public static final int MAJORAMOUNTZNH = AttributesEnum.MajorAmountZnh.index();
    public static final int MAJORAMOUNTOTHERS = AttributesEnum.MajorAmountOthers.index();
    public static final int LEFTCONFIRMAMOUNT = AttributesEnum.LeftConfirmAmount.index();
    public static final int CURRENTOWNERCONFIRMQUANTITIES = AttributesEnum.CurrentOwnerConfirmQuantities.index();
    public static final int CURRENTOTHERSUBCNTROUTPUT = AttributesEnum.CurrentOtherSubCntrOutput.index();
    public static final int CURRENTACTUALOUTPUT = AttributesEnum.CurrentActualOutput.index();
    public static final int CURRENTPROSUBCNTROUTPUT = AttributesEnum.CurrentProSubcntrOutput.index();
    public static final int CURRENTLABORAMOUNT = AttributesEnum.CurrentLaborAmount.index();
    public static final int CURRENTCNTRPAYMENTAMOUNT = AttributesEnum.CurrentCntrPaymentAmount.index();
    public static final int CURRENTSECURITYAMOUNT = AttributesEnum.CurrentSecurityAmount.index();
    public static final int CURRENTACTUALPAYMENTAMOUNT = AttributesEnum.CurrentActualPaymentAmount.index();
    public static final int CURRENTLEFTCONFIRMAMOUNT = AttributesEnum.CurrentLeftConfirmAmount.index();
    public static final int CURRENTALREADYCONFIRMAMOUNT = AttributesEnum.CurrentAlreadyConfirmAmount.index();
    public static final int CURRENTVISACONFIRMQUANTITY = AttributesEnum.CurrentVisaConfirmQuantity.index();
    public static final int CONFIRMVALUE = AttributesEnum.ConfirmValue.index();
    public static final int BMCNTRVERIFYLINET = AttributesEnum.BmCntrVerifyLineT.index();
    public static final int STATUSLOOKUPLOVVO1 = AttributesEnum.StatusLookupLovVO1.index();
    public static final int STMCONTRACTHEADERSLOVVO1 = AttributesEnum.StmContractHeadersLovVO1.index();
    public static final int STMCUSTOMERSANDSITSLOVVO1 = AttributesEnum.StmCustomersAndSitsLovVO1.index();
    public static final int STMCONFIRMEDCNTRLOVVO1 = AttributesEnum.StmConfirmedCntrLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrVerifyHeaderTVORowImpl() {
    }

    /**
     * Gets BmCntrVerifyHeaderTEO entity object.
     * @return the BmCntrVerifyHeaderTEO
     */
    public oracle.jbo.server.EntityImpl getBmCntrVerifyHeaderTEO() {
        return (oracle.jbo.server.EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CNTR_ID using the alias name CntrId.
     * @return the CNTR_ID
     */
    public Number getCntrId() {
        return (Number)getAttributeInternal(CNTRID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_ID using the alias name CntrId.
     * @param value value to set the CNTR_ID
     */
    public void setCntrId(Number value) {
        setAttributeInternal(CNTRID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrNumber.
     * @return the CntrNumber
     */
    public String getCntrNumber() {
        return (String)getAttributeInternal(CNTRNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrNumber.
     * @param value value to set the  CntrNumber
     */
    public void setCntrNumber(String value) {
        setAttributeInternal(CNTRNUMBER, value);
    }

    /**
     * Gets the attribute value for VERIFY_START_DATE using the alias name VerifyStartDate.
     * @return the VERIFY_START_DATE
     */
    public Date getVerifyStartDate() {
        return (Date)getAttributeInternal(VERIFYSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERIFY_START_DATE using the alias name VerifyStartDate.
     * @param value value to set the VERIFY_START_DATE
     */
    public void setVerifyStartDate(Date value) {
        setAttributeInternal(VERIFYSTARTDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrName.
     * @return the CntrName
     */
    public String getCntrName() {
        return (String)getAttributeInternal(CNTRNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrName.
     * @param value value to set the  CntrName
     */
    public void setCntrName(String value) {
        setAttributeInternal(CNTRNAME, value);
    }

    /**
     * Gets the attribute value for VERIFY_END_DATE using the alias name VerifyEndDate.
     * @return the VERIFY_END_DATE
     */
    public Date getVerifyEndDate() {
        return (Date)getAttributeInternal(VERIFYENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERIFY_END_DATE using the alias name VerifyEndDate.
     * @param value value to set the VERIFY_END_DATE
     */
    public void setVerifyEndDate(Date value) {
        setAttributeInternal(VERIFYENDDATE, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
     * @return the DOCUMENT_NUMBER
     */
    public String getDocumentNumber() {
        return (String)getAttributeInternal(DOCUMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
     * @param value value to set the DOCUMENT_NUMBER
     */
    public void setDocumentNumber(String value) {
        setAttributeInternal(DOCUMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public Number getCustomerId() {
        return (Number)getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String)getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerNumber.
     * @return the CustomerNumber
     */
    public String getCustomerNumber() {
        return (String)getAttributeInternal(CUSTOMERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerNumber.
     * @param value value to set the  CustomerNumber
     */
    public void setCustomerNumber(String value) {
        setAttributeInternal(CUSTOMERNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectNumber.
     * @return the ProjectNumber
     */
    public String getProjectNumber() {
        return (String)getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectNumber.
     * @param value value to set the  ProjectNumber
     */
    public void setProjectNumber(String value) {
        setAttributeInternal(PROJECTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectName.
     * @return the ProjectName
     */
    public String getProjectName() {
        return (String)getAttributeInternal(PROJECTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectName.
     * @param value value to set the  ProjectName
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**
     * Gets the attribute value for ACTUAL_CONFIRM_DATE using the alias name ActualConfirmDate.
     * @return the ACTUAL_CONFIRM_DATE
     */
    public Date getActualConfirmDate() {
        return (Date)getAttributeInternal(ACTUALCONFIRMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_CONFIRM_DATE using the alias name ActualConfirmDate.
     * @param value value to set the ACTUAL_CONFIRM_DATE
     */
    public void setActualConfirmDate(Date value) {
        setAttributeInternal(ACTUALCONFIRMDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OwnerMeasureDelayTime.
     * @return the OwnerMeasureDelayTime
     */
    public Number getOwnerMeasureDelayTime() {
        return (Number) getAttributeInternal(OWNERMEASUREDELAYTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OwnerMeasureDelayTime.
     * @param value value to set the  OwnerMeasureDelayTime
     */
    public void setOwnerMeasureDelayTime(Number value) {
        setAttributeInternal(OWNERMEASUREDELAYTIME, value);
    }

    /**
     * Gets the attribute value for ACTUAL_OUTPUT using the alias name ActualOutput.
     * @return the ACTUAL_OUTPUT
     */
    public Number getActualOutput() {
        return (Number)getAttributeInternal(ACTUALOUTPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_OUTPUT using the alias name ActualOutput.
     * @param value value to set the ACTUAL_OUTPUT
     */
    public void setActualOutput(Number value) {
        setAttributeInternal(ACTUALOUTPUT, value);
    }

    /**
     * Gets the attribute value for ACTUAL_PAYMENT_AMOUNT using the alias name ActualPaymentAmount.
     * @return the ACTUAL_PAYMENT_AMOUNT
     */
    public Number getActualPaymentAmount() {
        return (Number)getAttributeInternal(ACTUALPAYMENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_PAYMENT_AMOUNT using the alias name ActualPaymentAmount.
     * @param value value to set the ACTUAL_PAYMENT_AMOUNT
     */
    public void setActualPaymentAmount(Number value) {
        setAttributeInternal(ACTUALPAYMENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AlreadyConfirmAmount.
     * @return the AlreadyConfirmAmount
     */
    public Number getAlreadyConfirmAmount() {
        return (Number) getAttributeInternal(ALREADYCONFIRMAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AlreadyConfirmAmount.
     * @param value value to set the  AlreadyConfirmAmount
     */
    public void setAlreadyConfirmAmount(Number value) {
        setAttributeInternal(ALREADYCONFIRMAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LeftConfirmAmount.
     * @return the LeftConfirmAmount
     */
    public Number getLeftConfirmAmount() {
        return (Number) getAttributeInternal(LEFTCONFIRMAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LeftConfirmAmount.
     * @param value value to set the  LeftConfirmAmount
     */
    public void setLeftConfirmAmount(Number value) {
        setAttributeInternal(LEFTCONFIRMAMOUNT, value);
    }

    /**
     * Gets the attribute value for ACTUAL_PAYMENT_DATE using the alias name ActualPaymentDate.
     * @return the ACTUAL_PAYMENT_DATE
     */
    public Date getActualPaymentDate() {
        return (Date)getAttributeInternal(ACTUALPAYMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_PAYMENT_DATE using the alias name ActualPaymentDate.
     * @param value value to set the ACTUAL_PAYMENT_DATE
     */
    public void setActualPaymentDate(Date value) {
        setAttributeInternal(ACTUALPAYMENTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OwnerPaymentDelayTime.
     * @return the OwnerPaymentDelayTime
     */
    public Number getOwnerPaymentDelayTime() {
        return (Number) getAttributeInternal(OWNERPAYMENTDELAYTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OwnerPaymentDelayTime.
     * @param value value to set the  OwnerPaymentDelayTime
     */
    public void setOwnerPaymentDelayTime(Number value) {
        setAttributeInternal(OWNERPAYMENTDELAYTIME, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for CNTR_CONFIRM_DATE using the alias name CntrConfirmDate.
     * @return the CNTR_CONFIRM_DATE
     */
    public Date getCntrConfirmDate() {
        return (Date)getAttributeInternal(CNTRCONFIRMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_CONFIRM_DATE using the alias name CntrConfirmDate.
     * @param value value to set the CNTR_CONFIRM_DATE
     */
    public void setCntrConfirmDate(Date value) {
        setAttributeInternal(CNTRCONFIRMDATE, value);
    }

    /**
     * Gets the attribute value for CNTR_PAYMENT_AMOUNT using the alias name CntrPaymentAmount.
     * @return the CNTR_PAYMENT_AMOUNT
     */
    public Number getCntrPaymentAmount() {
        return (Number)getAttributeInternal(CNTRPAYMENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_PAYMENT_AMOUNT using the alias name CntrPaymentAmount.
     * @param value value to set the CNTR_PAYMENT_AMOUNT
     */
    public void setCntrPaymentAmount(Number value) {
        setAttributeInternal(CNTRPAYMENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for CNTR_PAYMENT_DATE using the alias name CntrPaymentDate.
     * @return the CNTR_PAYMENT_DATE
     */
    public Date getCntrPaymentDate() {
        return (Date)getAttributeInternal(CNTRPAYMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_PAYMENT_DATE using the alias name CntrPaymentDate.
     * @param value value to set the CNTR_PAYMENT_DATE
     */
    public void setCntrPaymentDate(Date value) {
        setAttributeInternal(CNTRPAYMENTDATE, value);
    }

    /**
     * Gets the attribute value for CNTR_VERIFY_HEADER_ID using the alias name CntrVerifyHeaderId.
     * @return the CNTR_VERIFY_HEADER_ID
     */
    public Number getCntrVerifyHeaderId() {
        return (Number)getAttributeInternal(CNTRVERIFYHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_VERIFY_HEADER_ID using the alias name CntrVerifyHeaderId.
     * @param value value to set the CNTR_VERIFY_HEADER_ID
     */
    public void setCntrVerifyHeaderId(Number value) {
        setAttributeInternal(CNTRVERIFYHEADERID, value);
    }

    /**
     * Gets the attribute value for CNTR_VISA_CONFIRM_QUANTITY using the alias name CntrVisaConfirmQuantity.
     * @return the CNTR_VISA_CONFIRM_QUANTITY
     */
    public Number getCntrVisaConfirmQuantity() {
        return (Number)getAttributeInternal(CNTRVISACONFIRMQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_VISA_CONFIRM_QUANTITY using the alias name CntrVisaConfirmQuantity.
     * @param value value to set the CNTR_VISA_CONFIRM_QUANTITY
     */
    public void setCntrVisaConfirmQuantity(Number value) {
        setAttributeInternal(CNTRVISACONFIRMQUANTITY, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LABOR_AMOUNT using the alias name LaborAmount.
     * @return the LABOR_AMOUNT
     */
    public Number getLaborAmount() {
        return (Number)getAttributeInternal(LABORAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for LABOR_AMOUNT using the alias name LaborAmount.
     * @param value value to set the LABOR_AMOUNT
     */
    public void setLaborAmount(Number value) {
        setAttributeInternal(LABORAMOUNT, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for OTHER_SUBCNTR_OUTPUT using the alias name OtherSubcntrOutput.
     * @return the OTHER_SUBCNTR_OUTPUT
     */
    public Number getOtherSubcntrOutput() {
        return (Number)getAttributeInternal(OTHERSUBCNTROUTPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_SUBCNTR_OUTPUT using the alias name OtherSubcntrOutput.
     * @param value value to set the OTHER_SUBCNTR_OUTPUT
     */
    public void setOtherSubcntrOutput(Number value) {
        setAttributeInternal(OTHERSUBCNTROUTPUT, value);
    }

    /**
     * Gets the attribute value for OWER_CONFIRM_QUANTITY using the alias name OwerConfirmQuantity.
     * @return the OWER_CONFIRM_QUANTITY
     */
    public Number getOwerConfirmQuantity() {
        return (Number)getAttributeInternal(OWERCONFIRMQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for OWER_CONFIRM_QUANTITY using the alias name OwerConfirmQuantity.
     * @param value value to set the OWER_CONFIRM_QUANTITY
     */
    public void setOwerConfirmQuantity(Number value) {
        setAttributeInternal(OWERCONFIRMQUANTITY, value);
    }

    /**
     * Gets the attribute value for PREPARED_BY using the alias name PreparedBy.
     * @return the PREPARED_BY
     */
    public Number getPreparedBy() {
        return (Number)getAttributeInternal(PREPAREDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for PREPARED_BY using the alias name PreparedBy.
     * @param value value to set the PREPARED_BY
     */
    public void setPreparedBy(Number value) {
        setAttributeInternal(PREPAREDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PreparedByName.
     * @return the PreparedByName
     */
    public String getPreparedByName() {
        return (String) getAttributeInternal(PREPAREDBYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PreparedByName.
     * @param value value to set the  PreparedByName
     */
    public void setPreparedByName(String value) {
        setAttributeInternal(PREPAREDBYNAME, value);
    }

    /**
     * Gets the attribute value for PREPARED_DATE using the alias name PreparedDate.
     * @return the PREPARED_DATE
     */
    public Date getPreparedDate() {
        return (Date)getAttributeInternal(PREPAREDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PREPARED_DATE using the alias name PreparedDate.
     * @param value value to set the PREPARED_DATE
     */
    public void setPreparedDate(Date value) {
        setAttributeInternal(PREPAREDDATE, value);
    }

    /**
     * Gets the attribute value for PRO_SUBCNTR_OUTPUT using the alias name ProSubcntrOutput.
     * @return the PRO_SUBCNTR_OUTPUT
     */
    public Number getProSubcntrOutput() {
        return (Number)getAttributeInternal(PROSUBCNTROUTPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRO_SUBCNTR_OUTPUT using the alias name ProSubcntrOutput.
     * @param value value to set the PRO_SUBCNTR_OUTPUT
     */
    public void setProSubcntrOutput(Number value) {
        setAttributeInternal(PROSUBCNTROUTPUT, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Number getProjectId() {
        return (Number)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for SECURITY_AMOUNT using the alias name SecurityAmount.
     * @return the SECURITY_AMOUNT
     */
    public Number getSecurityAmount() {
        return (Number)getAttributeInternal(SECURITYAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for SECURITY_AMOUNT using the alias name SecurityAmount.
     * @param value value to set the SECURITY_AMOUNT
     */
    public void setSecurityAmount(Number value) {
        setAttributeInternal(SECURITYAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentOwnerConfirmQuantities.
     * @return the CurrentOwnerConfirmQuantities
     */
    public Number getCurrentOwnerConfirmQuantities() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentOwnerConfirmQuantities();

        // return (Number) getAttributeInternal(CURRENTOWNERCONFIRMQUANTITIES);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentOwnerConfirmQuantities.
     * @param value value to set the  CurrentOwnerConfirmQuantities
     */
    public void setCurrentOwnerConfirmQuantities(Number value) {
        setAttributeInternal(CURRENTOWNERCONFIRMQUANTITIES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentOtherSubCntrOutput.
     * @return the CurrentOtherSubCntrOutput
     */
    public Number getCurrentOtherSubCntrOutput() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentOtherSubCntrOutput();

        //    return (Number) getAttributeInternal(CURRENTOTHERSUBCNTROUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentOtherSubCntrOutput.
     * @param value value to set the  CurrentOtherSubCntrOutput
     */
    public void setCurrentOtherSubCntrOutput(Number value) {
        setAttributeInternal(CURRENTOTHERSUBCNTROUTPUT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentActualOutput.
     * @return the CurrentActualOutput
     */
    public Number getCurrentActualOutput() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentActualOutput();
        //return (Number) getAttributeInternal(CURRENTACTUALOUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentActualOutput.
     * @param value value to set the  CurrentActualOutput
     */
    public void setCurrentActualOutput(Number value) {
        setAttributeInternal(CURRENTACTUALOUTPUT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentProSubcntrOutput.
     * @return the CurrentProSubcntrOutput
     */
    public Number getCurrentProSubcntrOutput() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentProSubcntrOutput();
        //return (Number) getAttributeInternal(CURRENTPROSUBCNTROUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentProSubcntrOutput.
     * @param value value to set the  CurrentProSubcntrOutput
     */
    public void setCurrentProSubcntrOutput(Number value) {
        setAttributeInternal(CURRENTPROSUBCNTROUTPUT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentLaborAmount.
     * @return the CurrentLaborAmount
     */
    public Number getCurrentLaborAmount() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentLaborAmount();
        //return (Number) getAttributeInternal(CURRENTLABORAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentLaborAmount.
     * @param value value to set the  CurrentLaborAmount
     */
    public void setCurrentLaborAmount(Number value) {
        setAttributeInternal(CURRENTLABORAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentCntrPaymentAmount.
     * @return the CurrentCntrPaymentAmount
     */
    public Number getCurrentCntrPaymentAmount() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentCntrPaymentAmount();
        //return (Number) getAttributeInternal(CURRENTCNTRPAYMENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentCntrPaymentAmount.
     * @param value value to set the  CurrentCntrPaymentAmount
     */
    public void setCurrentCntrPaymentAmount(Number value) {
        setAttributeInternal(CURRENTCNTRPAYMENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSecurityAmount.
     * @return the CurrentSecurityAmount
     */
    public Number getCurrentSecurityAmount() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentSecurityAmount();
        //return (Number) getAttributeInternal(CURRENTSECURITYAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSecurityAmount.
     * @param value value to set the  CurrentSecurityAmount
     */
    public void setCurrentSecurityAmount(Number value) {
        setAttributeInternal(CURRENTSECURITYAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentActualPaymentAmount.
     * @return the CurrentActualPaymentAmount
     */
    public Number getCurrentActualPaymentAmount() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentActualPaymentAmount();
        //return (Number) getAttributeInternal(CURRENTACTUALPAYMENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentActualPaymentAmount.
     * @param value value to set the  CurrentActualPaymentAmount
     */
    public void setCurrentActualPaymentAmount(Number value) {
        setAttributeInternal(CURRENTACTUALPAYMENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentLeftConfirmAmount.
     * @return the CurrentLeftConfirmAmount
     */
    public Number getCurrentLeftConfirmAmount() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentLeftConfirmAmount();

   //     return (Number) getAttributeInternal(CURRENTLEFTCONFIRMAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentLeftConfirmAmount.
     * @param value value to set the  CurrentLeftConfirmAmount
     */
    public void setCurrentLeftConfirmAmount(Number value) {
        setAttributeInternal(CURRENTLEFTCONFIRMAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentAlreadyConfirmAmount.
     * @return the CurrentAlreadyConfirmAmount
     */
    public Number getCurrentAlreadyConfirmAmount() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentAlreadyConfirmAmount();

  //      return (Number) getAttributeInternal(CURRENTALREADYCONFIRMAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentAlreadyConfirmAmount.
     * @param value value to set the  CurrentAlreadyConfirmAmount
     */
    public void setCurrentAlreadyConfirmAmount(Number value) {
        setAttributeInternal(CURRENTALREADYCONFIRMAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentVisaConfirmQuantity.
     * @return the CurrentVisaConfirmQuantity
     */
    public Number getCurrentVisaConfirmQuantity() {
        return ((BmCntrVerifyHeaderTVOImpl)getViewObject()).getCurrentVisaConfirmQuantity();

      //  return (Number) getAttributeInternal(CURRENTVISACONFIRMQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentVisaConfirmQuantity.
     * @param value value to set the  CurrentVisaConfirmQuantity
     */
    public void setCurrentVisaConfirmQuantity(Number value) {
        setAttributeInternal(CURRENTVISACONFIRMQUANTITY, value);
    }


    /**
     * Gets the attribute value for CUMULATIVE_WITHHOLD_AMOUNT using the alias name CumulativeWithholdAmount.
     * @return the CUMULATIVE_WITHHOLD_AMOUNT
     */
    public Number getCumulativeWithholdAmount() {
        return (Number) getAttributeInternal(CUMULATIVEWITHHOLDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CUMULATIVE_WITHHOLD_AMOUNT using the alias name CumulativeWithholdAmount.
     * @param value value to set the CUMULATIVE_WITHHOLD_AMOUNT
     */
    public void setCumulativeWithholdAmount(Number value) {
        setAttributeInternal(CUMULATIVEWITHHOLDAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ConfirmValue.
     * @return the ConfirmValue
     */
    public Number getConfirmValue() {
        return (Number) getAttributeInternal(CONFIRMVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ConfirmValue.
     * @param value value to set the  ConfirmValue
     */
    public void setConfirmValue(Number value) {
        setAttributeInternal(CONFIRMVALUE, value);
    }

    /**
     * Gets the attribute value for MAJOR_AMOUNT_AZ using the alias name MajorAmountAz.
     * @return the MAJOR_AMOUNT_AZ
     */
    public Number getMajorAmountAz() {
        return (Number) getAttributeInternal(MAJORAMOUNTAZ);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_AMOUNT_AZ using the alias name MajorAmountAz.
     * @param value value to set the MAJOR_AMOUNT_AZ
     */
    public void setMajorAmountAz(Number value) {
        setAttributeInternal(MAJORAMOUNTAZ, value);
    }

    /**
     * Gets the attribute value for MAJOR_AMOUNT_GJG using the alias name MajorAmountGjg.
     * @return the MAJOR_AMOUNT_GJG
     */
    public Number getMajorAmountGjg() {
        return (Number) getAttributeInternal(MAJORAMOUNTGJG);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_AMOUNT_GJG using the alias name MajorAmountGjg.
     * @param value value to set the MAJOR_AMOUNT_GJG
     */
    public void setMajorAmountGjg(Number value) {
        setAttributeInternal(MAJORAMOUNTGJG, value);
    }

    /**
     * Gets the attribute value for MAJOR_AMOUNT_OTHERS using the alias name MajorAmountOthers.
     * @return the MAJOR_AMOUNT_OTHERS
     */
    public Number getMajorAmountOthers() {
        return (Number) getAttributeInternal(MAJORAMOUNTOTHERS);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_AMOUNT_OTHERS using the alias name MajorAmountOthers.
     * @param value value to set the MAJOR_AMOUNT_OTHERS
     */
    public void setMajorAmountOthers(Number value) {
        setAttributeInternal(MAJORAMOUNTOTHERS, value);
    }

    /**
     * Gets the attribute value for MAJOR_AMOUNT_TJ using the alias name MajorAmountTj.
     * @return the MAJOR_AMOUNT_TJ
     */
    public Number getMajorAmountTj() {
        return (Number) getAttributeInternal(MAJORAMOUNTTJ);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_AMOUNT_TJ using the alias name MajorAmountTj.
     * @param value value to set the MAJOR_AMOUNT_TJ
     */
    public void setMajorAmountTj(Number value) {
        setAttributeInternal(MAJORAMOUNTTJ, value);
    }

    /**
     * Gets the attribute value for MAJOR_AMOUNT_ZNH using the alias name MajorAmountZnh.
     * @return the MAJOR_AMOUNT_ZNH
     */
    public Number getMajorAmountZnh() {
        return (Number) getAttributeInternal(MAJORAMOUNTZNH);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_AMOUNT_ZNH using the alias name MajorAmountZnh.
     * @param value value to set the MAJOR_AMOUNT_ZNH
     */
    public void setMajorAmountZnh(Number value) {
        setAttributeInternal(MAJORAMOUNTZNH, value);
    }

    /**
     * Gets the attribute value for MAJOR_AMOUNT_ZS using the alias name MajorAmountZs.
     * @return the MAJOR_AMOUNT_ZS
     */
    public Number getMajorAmountZs() {
        return (Number) getAttributeInternal(MAJORAMOUNTZS);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_AMOUNT_ZS using the alias name MajorAmountZs.
     * @param value value to set the MAJOR_AMOUNT_ZS
     */
    public void setMajorAmountZs(Number value) {
        setAttributeInternal(MAJORAMOUNTZS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxRate.
     * @return the TaxRate
     */
    public String getTaxRate() {
        return (String) getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxRate.
     * @param value value to set the  TaxRate
     */
    public void setTaxRate(String value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for CUMULATIVE_ACTUAL_OUTPUT using the alias name CumulativeActualOutput.
     * @return the CUMULATIVE_ACTUAL_OUTPUT
     */
    public Number getCumulativeActualOutput() {
        return (Number) getAttributeInternal(CUMULATIVEACTUALOUTPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for CUMULATIVE_ACTUAL_OUTPUT using the alias name CumulativeActualOutput.
     * @param value value to set the CUMULATIVE_ACTUAL_OUTPUT
     */
    public void setCumulativeActualOutput(Number value) {
        setAttributeInternal(CUMULATIVEACTUALOUTPUT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BmCntrVerifyLineT.
     */
    public RowIterator getBmCntrVerifyLineT() {
        return (RowIterator)getAttributeInternal(BMCNTRVERIFYLINET);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StatusLookupLovVO1.
     */
    public RowSet getStatusLookupLovVO1() {
        return (RowSet)getAttributeInternal(STATUSLOOKUPLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StmContractHeadersLovVO1.
     */
    public RowSet getStmContractHeadersLovVO1() {
        return (RowSet)getAttributeInternal(STMCONTRACTHEADERSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StmCustomersAndSitsLovVO1.
     */
    public RowSet getStmCustomersAndSitsLovVO1() {
        return (RowSet)getAttributeInternal(STMCUSTOMERSANDSITSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StmConfirmedCntrLovVO1.
     */
    public RowSet getStmConfirmedCntrLovVO1() {
        return (RowSet)getAttributeInternal(STMCONFIRMEDCNTRLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
