package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomViewObjectImpl;

import oracle.jbo.server.SQLBuilder;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 21 07:07:46 CST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrMeasureLineTVOImpl extends CustomViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrMeasureLineTVOImpl() {
    }

//    public void executeQueryForCollection(Object rowset, Object[] params,
//                                          int noUserParams) {
//        System.out.println("VO name: " + this.getFullName());
//        System.out.println("Query is: " + this.getQuery());
//        getParametersValues(params);
//        super.executeQueryForCollection(rowset, params, noUserParams);
//    }
//
//    private void getParametersValues(Object[] params) {
//        if (getBindingStyle() == SQLBuilder.BINDING_STYLE_ORACLE_NAME) {
//            if (params != null) {
//                for (Object param : params) {
//                    Object[] value = (Object[])param;
//                    System.out.println("Name=" + value[0] + "; Value=" +
//                                       value[1]);
//                }
//            }
//        }
//    }
}
