package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomEntityImpl;
import cn.com.cscec8b.framework.model.common.CustomViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 16:57:24 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrMeasureHeaderTVORowImpl extends CustomViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CntrMeasureHeaderId {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCntrMeasureHeaderId();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCntrMeasureHeaderId((Number)value);
            }
        }
        ,
        CntrNumber {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCntrNumber();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCntrNumber((String)value);
            }
        }
        ,
        MeasureStartTime {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getMeasureStartTime();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setMeasureStartTime((Date)value);
            }
        }
        ,
        Status {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        CntrName {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCntrName();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCntrName((String)value);
            }
        }
        ,
        MeasureEndTime {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getMeasureEndTime();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setMeasureEndTime((Date)value);
            }
        }
        ,
        DocumentNumber {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getDocumentNumber();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setDocumentNumber((String)value);
            }
        }
        ,
        CustomerName {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        ProjectId {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setProjectId((Number)value);
            }
        }
        ,
        ProjectNumber {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getProjectNumber();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setProjectNumber((String)value);
            }
        }
        ,
        ProjectName {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getProjectName();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setProjectName((String)value);
            }
        }
        ,
        CntrId {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCntrId();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCntrId((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        CustomerNumber {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCustomerNumber();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCustomerNumber((String)value);
            }
        }
        ,
        PreparedBy {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getPreparedBy();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setPreparedBy((Number)value);
            }
        }
        ,
        PreparedByName {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getPreparedByName();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setPreparedByName((String)value);
            }
        }
        ,
        PreparedDate {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getPreparedDate();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setPreparedDate((Date)value);
            }
        }
        ,
        CntrListNumber {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCntrListNumber();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCntrListNumber((String)value);
            }
        }
        ,
        ProductionTotal {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getProductionTotal();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setProductionTotal((Number)value);
            }
        }
        ,
        ProductionProSubcntr {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getProductionProSubcntr();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setProductionProSubcntr((Number)value);
            }
        }
        ,
        AccountFlag {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAccountFlag();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAccountFlag((String)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Comments {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getComments();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        GraphicProgress {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getGraphicProgress();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setGraphicProgress((String)value);
            }
        }
        ,
        MeasureDate {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getMeasureDate();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setMeasureDate((Date)value);
            }
        }
        ,
        CntrVerifyHeaderId {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCntrVerifyHeaderId();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCntrVerifyHeaderId((Number)value);
            }
        }
        ,
        CvhDocno {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCvhDocno();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCvhDocno((String)value);
            }
        }
        ,
        VerifyStartDate {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getVerifyStartDate();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setVerifyStartDate((Date)value);
            }
        }
        ,
        VerifyEndDate {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getVerifyEndDate();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setVerifyEndDate((Date)value);
            }
        }
        ,
        OwerConfirmQuantity {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getOwerConfirmQuantity();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setOwerConfirmQuantity((Number)value);
            }
        }
        ,
        OtherSubcntrOutput {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getOtherSubcntrOutput();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setOtherSubcntrOutput((Number)value);
            }
        }
        ,
        CntrVisaConfirmQuantity {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCntrVisaConfirmQuantity();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCntrVisaConfirmQuantity((Number)value);
            }
        }
        ,
        VeCntrMeasureHeaderId {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getVeCntrMeasureHeaderId();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setVeCntrMeasureHeaderId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ProSubcntrFlag {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getProSubcntrFlag();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setProSubcntrFlag((String)value);
            }
        }
        ,
        VatAmount {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getVatAmount();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setVatAmount((Number)value);
            }
        }
        ,
        TaxRate {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getTaxRate();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setTaxRate((String)value);
            }
        }
        ,
        CheckedFlag {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCheckedFlag();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCheckedFlag((String)value);
            }
        }
        ,
        SumProductionTotal {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getSumProductionTotal();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setSumProductionTotal((Number)value);
            }
        }
        ,
        SumOtherSubcntrOutput {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getSumOtherSubcntrOutput();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setSumOtherSubcntrOutput((Number)value);
            }
        }
        ,
        SumOwerConfirmQuantity {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getSumOwerConfirmQuantity();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setSumOwerConfirmQuantity((Number)value);
            }
        }
        ,
        SumCntrVisaConfirmQuantity {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getSumCntrVisaConfirmQuantity();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setSumCntrVisaConfirmQuantity((Number)value);
            }
        }
        ,
        CumulativeProductionAmount {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getCumulativeProductionAmount();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setCumulativeProductionAmount((Number)value);
            }
        }
        ,
        BmCntrMeasureLineT {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getBmCntrMeasureLineT();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StatusLookupLovVO1 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getStatusLookupLovVO1();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ListHeaderLovVO1 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getListHeaderLovVO1();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmCustomersAndSitsLovVO1 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getStmCustomersAndSitsLovVO1();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        YesOrNoLookupLovVO1 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getYesOrNoLookupLovVO1();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmConfirmedCntrLovVO1 {
            public Object get(BmCntrMeasureHeaderTVORowImpl obj) {
                return obj.getStmConfirmedCntrLovVO1();
            }

            public void put(BmCntrMeasureHeaderTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BmCntrMeasureHeaderTVORowImpl object);

        public abstract void put(BmCntrMeasureHeaderTVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CNTRMEASUREHEADERID = AttributesEnum.CntrMeasureHeaderId.index();
    public static final int CNTRNUMBER = AttributesEnum.CntrNumber.index();
    public static final int MEASURESTARTTIME = AttributesEnum.MeasureStartTime.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CNTRNAME = AttributesEnum.CntrName.index();
    public static final int MEASUREENDTIME = AttributesEnum.MeasureEndTime.index();
    public static final int DOCUMENTNUMBER = AttributesEnum.DocumentNumber.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int PROJECTNUMBER = AttributesEnum.ProjectNumber.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int CNTRID = AttributesEnum.CntrId.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNUMBER = AttributesEnum.CustomerNumber.index();
    public static final int PREPAREDBY = AttributesEnum.PreparedBy.index();
    public static final int PREPAREDBYNAME = AttributesEnum.PreparedByName.index();
    public static final int PREPAREDDATE = AttributesEnum.PreparedDate.index();
    public static final int CNTRLISTNUMBER = AttributesEnum.CntrListNumber.index();
    public static final int PRODUCTIONTOTAL = AttributesEnum.ProductionTotal.index();
    public static final int PRODUCTIONPROSUBCNTR = AttributesEnum.ProductionProSubcntr.index();
    public static final int ACCOUNTFLAG = AttributesEnum.AccountFlag.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int GRAPHICPROGRESS = AttributesEnum.GraphicProgress.index();
    public static final int MEASUREDATE = AttributesEnum.MeasureDate.index();
    public static final int CNTRVERIFYHEADERID = AttributesEnum.CntrVerifyHeaderId.index();
    public static final int CVHDOCNO = AttributesEnum.CvhDocno.index();
    public static final int VERIFYSTARTDATE = AttributesEnum.VerifyStartDate.index();
    public static final int VERIFYENDDATE = AttributesEnum.VerifyEndDate.index();
    public static final int OWERCONFIRMQUANTITY = AttributesEnum.OwerConfirmQuantity.index();
    public static final int OTHERSUBCNTROUTPUT = AttributesEnum.OtherSubcntrOutput.index();
    public static final int CNTRVISACONFIRMQUANTITY = AttributesEnum.CntrVisaConfirmQuantity.index();
    public static final int VECNTRMEASUREHEADERID = AttributesEnum.VeCntrMeasureHeaderId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PROSUBCNTRFLAG = AttributesEnum.ProSubcntrFlag.index();
    public static final int VATAMOUNT = AttributesEnum.VatAmount.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int CHECKEDFLAG = AttributesEnum.CheckedFlag.index();
    public static final int SUMPRODUCTIONTOTAL = AttributesEnum.SumProductionTotal.index();
    public static final int SUMOTHERSUBCNTROUTPUT = AttributesEnum.SumOtherSubcntrOutput.index();
    public static final int SUMOWERCONFIRMQUANTITY = AttributesEnum.SumOwerConfirmQuantity.index();
    public static final int SUMCNTRVISACONFIRMQUANTITY = AttributesEnum.SumCntrVisaConfirmQuantity.index();
    public static final int CUMULATIVEPRODUCTIONAMOUNT = AttributesEnum.CumulativeProductionAmount.index();
    public static final int BMCNTRMEASURELINET = AttributesEnum.BmCntrMeasureLineT.index();
    public static final int STATUSLOOKUPLOVVO1 = AttributesEnum.StatusLookupLovVO1.index();
    public static final int LISTHEADERLOVVO1 = AttributesEnum.ListHeaderLovVO1.index();
    public static final int STMCUSTOMERSANDSITSLOVVO1 = AttributesEnum.StmCustomersAndSitsLovVO1.index();
    public static final int YESORNOLOOKUPLOVVO1 = AttributesEnum.YesOrNoLookupLovVO1.index();
    public static final int STMCONFIRMEDCNTRLOVVO1 = AttributesEnum.StmConfirmedCntrLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrMeasureHeaderTVORowImpl() {
    }

    /**
     * Gets BmCntrMeasureHeaderTEO entity object.
     * @return the BmCntrMeasureHeaderTEO
     */
    public CustomEntityImpl getBmCntrMeasureHeaderTEO() {
        return (CustomEntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CNTR_MEASURE_HEADER_ID using the alias name CntrMeasureHeaderId.
     * @return the CNTR_MEASURE_HEADER_ID
     */
    public Number getCntrMeasureHeaderId() {
        return (Number) getAttributeInternal(CNTRMEASUREHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_MEASURE_HEADER_ID using the alias name CntrMeasureHeaderId.
     * @param value value to set the CNTR_MEASURE_HEADER_ID
     */
    public void setCntrMeasureHeaderId(Number value) {
        setAttributeInternal(CNTRMEASUREHEADERID, value);
    }


    /**
     * Gets the attribute value for the calculated attribute CntrNumber.
     * @return the CntrNumber
     */
    public String getCntrNumber() {
        return (String) getAttributeInternal(CNTRNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrNumber.
     * @param value value to set the  CntrNumber
     */
    public void setCntrNumber(String value) {
        setAttributeInternal(CNTRNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeasureStartTime.
     * @return the MeasureStartTime
     */
    public Date getMeasureStartTime() {
        return (Date) getAttributeInternal(MEASURESTARTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeasureStartTime.
     * @param value value to set the  MeasureStartTime
     */
    public void setMeasureStartTime(Date value) {
        setAttributeInternal(MEASURESTARTTIME, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrName.
     * @return the CntrName
     */
    public String getCntrName() {
        return (String) getAttributeInternal(CNTRNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrName.
     * @param value value to set the  CntrName
     */
    public void setCntrName(String value) {
        setAttributeInternal(CNTRNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeasureEndTime.
     * @return the MeasureEndTime
     */
    public Date getMeasureEndTime() {
        return (Date) getAttributeInternal(MEASUREENDTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeasureEndTime.
     * @param value value to set the  MeasureEndTime
     */
    public void setMeasureEndTime(Date value) {
        setAttributeInternal(MEASUREENDTIME, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
     * @return the DOCUMENT_NUMBER
     */
    public String getDocumentNumber() {
        return (String) getAttributeInternal(DOCUMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
     * @param value value to set the DOCUMENT_NUMBER
     */
    public void setDocumentNumber(String value) {
        setAttributeInternal(DOCUMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectNumber.
     * @return the ProjectNumber
     */
    public String getProjectNumber() {
        return (String) getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectNumber.
     * @param value value to set the  ProjectNumber
     */
    public void setProjectNumber(String value) {
        setAttributeInternal(PROJECTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectName.
     * @return the ProjectName
     */
    public String getProjectName() {
        return (String) getAttributeInternal(PROJECTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectName.
     * @param value value to set the  ProjectName
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**
     * Gets the attribute value for CNTR_ID using the alias name CntrId.
     * @return the CNTR_ID
     */
    public Number getCntrId() {
        return (Number) getAttributeInternal(CNTRID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_ID using the alias name CntrId.
     * @param value value to set the CNTR_ID
     */
    public void setCntrId(Number value) {
        setAttributeInternal(CNTRID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerNumber.
     * @return the CustomerNumber
     */
    public String getCustomerNumber() {
        return (String) getAttributeInternal(CUSTOMERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerNumber.
     * @param value value to set the  CustomerNumber
     */
    public void setCustomerNumber(String value) {
        setAttributeInternal(CUSTOMERNUMBER, value);
    }

    /**
     * Gets the attribute value for PREPARED_BY using the alias name PreparedBy.
     * @return the PREPARED_BY
     */
    public Number getPreparedBy() {
        return (Number) getAttributeInternal(PREPAREDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for PREPARED_BY using the alias name PreparedBy.
     * @param value value to set the PREPARED_BY
     */
    public void setPreparedBy(Number value) {
        setAttributeInternal(PREPAREDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PreparedByName.
     * @return the PreparedByName
     */
    public String getPreparedByName() {
        return (String) getAttributeInternal(PREPAREDBYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PreparedByName.
     * @param value value to set the  PreparedByName
     */
    public void setPreparedByName(String value) {
        setAttributeInternal(PREPAREDBYNAME, value);
    }

    /**
     * Gets the attribute value for PREPARED_DATE using the alias name PreparedDate.
     * @return the PREPARED_DATE
     */
    public Date getPreparedDate() {
        return (Date) getAttributeInternal(PREPAREDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PREPARED_DATE using the alias name PreparedDate.
     * @param value value to set the PREPARED_DATE
     */
    public void setPreparedDate(Date value) {
        setAttributeInternal(PREPAREDDATE, value);
    }

    /**
     * Gets the attribute value for CNTR_LIST_NUMBER using the alias name CntrListNumber.
     * @return the CNTR_LIST_NUMBER
     */
    public String getCntrListNumber() {
        return (String) getAttributeInternal(CNTRLISTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_LIST_NUMBER using the alias name CntrListNumber.
     * @param value value to set the CNTR_LIST_NUMBER
     */
    public void setCntrListNumber(String value) {
        setAttributeInternal(CNTRLISTNUMBER, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_TOTAL using the alias name ProductionTotal.
     * @return the PRODUCTION_TOTAL
     */
    public Number getProductionTotal() {
        return (Number) getAttributeInternal(PRODUCTIONTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_TOTAL using the alias name ProductionTotal.
     * @param value value to set the PRODUCTION_TOTAL
     */
    public void setProductionTotal(Number value) {
        setAttributeInternal(PRODUCTIONTOTAL, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_PRO_SUBCNTR using the alias name ProductionProSubcntr.
     * @return the PRODUCTION_PRO_SUBCNTR
     */
    public Number getProductionProSubcntr() {
        return (Number) getAttributeInternal(PRODUCTIONPROSUBCNTR);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_PRO_SUBCNTR using the alias name ProductionProSubcntr.
     * @param value value to set the PRODUCTION_PRO_SUBCNTR
     */
    public void setProductionProSubcntr(Number value) {
        setAttributeInternal(PRODUCTIONPROSUBCNTR, value);
    }

    /**
     * Gets the attribute value for ACCOUNT_FLAG using the alias name AccountFlag.
     * @return the ACCOUNT_FLAG
     */
    public String getAccountFlag() {
        return (String) getAttributeInternal(ACCOUNTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_FLAG using the alias name AccountFlag.
     * @param value value to set the ACCOUNT_FLAG
     */
    public void setAccountFlag(String value) {
        setAttributeInternal(ACCOUNTFLAG, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for GRAPHIC_PROGRESS using the alias name GraphicProgress.
     * @return the GRAPHIC_PROGRESS
     */
    public String getGraphicProgress() {
        return (String) getAttributeInternal(GRAPHICPROGRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for GRAPHIC_PROGRESS using the alias name GraphicProgress.
     * @param value value to set the GRAPHIC_PROGRESS
     */
    public void setGraphicProgress(String value) {
        setAttributeInternal(GRAPHICPROGRESS, value);
    }

    /**
     * Gets the attribute value for MEASURE_DATE using the alias name MeasureDate.
     * @return the MEASURE_DATE
     */
    public Date getMeasureDate() {
        return (Date) getAttributeInternal(MEASUREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_DATE using the alias name MeasureDate.
     * @param value value to set the MEASURE_DATE
     */
    public void setMeasureDate(Date value) {
        setAttributeInternal(MEASUREDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrVerifyHeaderId.
     * @return the CntrVerifyHeaderId
     */
    public Number getCntrVerifyHeaderId() {
        return (Number) getAttributeInternal(CNTRVERIFYHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrVerifyHeaderId.
     * @param value value to set the  CntrVerifyHeaderId
     */
    public void setCntrVerifyHeaderId(Number value) {
        setAttributeInternal(CNTRVERIFYHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CvhDocno.
     * @return the CvhDocno
     */
    public String getCvhDocno() {
        return (String) getAttributeInternal(CVHDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CvhDocno.
     * @param value value to set the  CvhDocno
     */
    public void setCvhDocno(String value) {
        setAttributeInternal(CVHDOCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VerifyStartDate.
     * @return the VerifyStartDate
     */
    public Date getVerifyStartDate() {
        return (Date) getAttributeInternal(VERIFYSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VerifyStartDate.
     * @param value value to set the  VerifyStartDate
     */
    public void setVerifyStartDate(Date value) {
        setAttributeInternal(VERIFYSTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VerifyEndDate.
     * @return the VerifyEndDate
     */
    public Date getVerifyEndDate() {
        return (Date) getAttributeInternal(VERIFYENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VerifyEndDate.
     * @param value value to set the  VerifyEndDate
     */
    public void setVerifyEndDate(Date value) {
        setAttributeInternal(VERIFYENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OwerConfirmQuantity.
     * @return the OwerConfirmQuantity
     */
    public Number getOwerConfirmQuantity() {
        return (Number) getAttributeInternal(OWERCONFIRMQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OwerConfirmQuantity.
     * @param value value to set the  OwerConfirmQuantity
     */
    public void setOwerConfirmQuantity(Number value) {
        setAttributeInternal(OWERCONFIRMQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OtherSubcntrOutput.
     * @return the OtherSubcntrOutput
     */
    public Number getOtherSubcntrOutput() {
        return (Number) getAttributeInternal(OTHERSUBCNTROUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OtherSubcntrOutput.
     * @param value value to set the  OtherSubcntrOutput
     */
    public void setOtherSubcntrOutput(Number value) {
        setAttributeInternal(OTHERSUBCNTROUTPUT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrVisaConfirmQuantity.
     * @return the CntrVisaConfirmQuantity
     */
    public Number getCntrVisaConfirmQuantity() {
        return (Number) getAttributeInternal(CNTRVISACONFIRMQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrVisaConfirmQuantity.
     * @param value value to set the  CntrVisaConfirmQuantity
     */
    public void setCntrVisaConfirmQuantity(Number value) {
        setAttributeInternal(CNTRVISACONFIRMQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VeCntrMeasureHeaderId.
     * @return the VeCntrMeasureHeaderId
     */
    public Number getVeCntrMeasureHeaderId() {
        return (Number) getAttributeInternal(VECNTRMEASUREHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VeCntrMeasureHeaderId.
     * @param value value to set the  VeCntrMeasureHeaderId
     */
    public void setVeCntrMeasureHeaderId(Number value) {
        setAttributeInternal(VECNTRMEASUREHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CheckedFlag.
     * @return the CheckedFlag
     */
    public String getCheckedFlag() {
        return (String) getAttributeInternal(CHECKEDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CheckedFlag.
     * @param value value to set the  CheckedFlag
     */
    public void setCheckedFlag(String value) {
        setAttributeInternal(CHECKEDFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumProductionTotal.
     * @return the SumProductionTotal
     */
    public Number getSumProductionTotal() {
        return ((BmCntrMeasureHeaderTVOImpl)getViewObject()).getSumProductionTotal();
      //  return (Number) getAttributeInternal(SUMPRODUCTIONTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumProductionTotal.
     * @param value value to set the  SumProductionTotal
     */
    public void setSumProductionTotal(Number value) {
        setAttributeInternal(SUMPRODUCTIONTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumOtherSubcntrOutput.
     * @return the SumOtherSubcntrOutput
     */
    public Number getSumOtherSubcntrOutput() {
        return ((BmCntrMeasureHeaderTVOImpl)getViewObject()).getSumOtherSubcntrOutput();

     //   return (Number) getAttributeInternal(SUMOTHERSUBCNTROUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumOtherSubcntrOutput.
     * @param value value to set the  SumOtherSubcntrOutput
     */
    public void setSumOtherSubcntrOutput(Number value) {
        setAttributeInternal(SUMOTHERSUBCNTROUTPUT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumOwerConfirmQuantity.
     * @return the SumOwerConfirmQuantity
     */
    public Number getSumOwerConfirmQuantity() {
        return ((BmCntrMeasureHeaderTVOImpl)getViewObject()).getSumOwerConfirmQuantity();

      //  return (Number) getAttributeInternal(SUMOWERCONFIRMQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumOwerConfirmQuantity.
     * @param value value to set the  SumOwerConfirmQuantity
     */
    public void setSumOwerConfirmQuantity(Number value) {
        setAttributeInternal(SUMOWERCONFIRMQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumCntrVisaConfirmQuantity.
     * @return the SumCntrVisaConfirmQuantity
     */
    public Number getSumCntrVisaConfirmQuantity() {
        return ((BmCntrMeasureHeaderTVOImpl)getViewObject()).getSumCntrVisaConfirmQuantity();

       // return (Number) getAttributeInternal(SUMCNTRVISACONFIRMQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumCntrVisaConfirmQuantity.
     * @param value value to set the  SumCntrVisaConfirmQuantity
     */
    public void setSumCntrVisaConfirmQuantity(Number value) {
        setAttributeInternal(SUMCNTRVISACONFIRMQUANTITY, value);
    }


    /**
     * Gets the attribute value for CUMULATIVE_PRODUCTION_AMOUNT using the alias name CumulativeProductionAmount.
     * @return the CUMULATIVE_PRODUCTION_AMOUNT
     */
    public Number getCumulativeProductionAmount() {
        return (Number) getAttributeInternal(CUMULATIVEPRODUCTIONAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CUMULATIVE_PRODUCTION_AMOUNT using the alias name CumulativeProductionAmount.
     * @param value value to set the CUMULATIVE_PRODUCTION_AMOUNT
     */
    public void setCumulativeProductionAmount(Number value) {
        setAttributeInternal(CUMULATIVEPRODUCTIONAMOUNT, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PRO_SUBCNTR_FLAG using the alias name ProSubcntrFlag.
     * @return the PRO_SUBCNTR_FLAG
     */
    public String getProSubcntrFlag() {
        return (String) getAttributeInternal(PROSUBCNTRFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PRO_SUBCNTR_FLAG using the alias name ProSubcntrFlag.
     * @param value value to set the PRO_SUBCNTR_FLAG
     */
    public void setProSubcntrFlag(String value) {
        setAttributeInternal(PROSUBCNTRFLAG, value);
    }

    /**
     * Gets the attribute value for VAT_AMOUNT using the alias name VatAmount.
     * @return the VAT_AMOUNT
     */
    public Number getVatAmount() {
        return (Number) getAttributeInternal(VATAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for VAT_AMOUNT using the alias name VatAmount.
     * @param value value to set the VAT_AMOUNT
     */
    public void setVatAmount(Number value) {
        setAttributeInternal(VATAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxRate.
     * @return the TaxRate
     */
    public String getTaxRate() {
        return (String) getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxRate.
     * @param value value to set the  TaxRate
     */
    public void setTaxRate(String value) {
        setAttributeInternal(TAXRATE, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BmCntrMeasureLineT.
     */
    public RowIterator getBmCntrMeasureLineT() {
        return (RowIterator)getAttributeInternal(BMCNTRMEASURELINET);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StatusLookupLovVO1.
     */
    public RowSet getStatusLookupLovVO1() {
        return (RowSet)getAttributeInternal(STATUSLOOKUPLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ListHeaderLovVO1.
     */
    public RowSet getListHeaderLovVO1() {
        return (RowSet)getAttributeInternal(LISTHEADERLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StmCustomersAndSitsLovVO1.
     */
    public RowSet getStmCustomersAndSitsLovVO1() {
        return (RowSet)getAttributeInternal(STMCUSTOMERSANDSITSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesOrNoLookupLovVO1.
     */
    public RowSet getYesOrNoLookupLovVO1() {
        return (RowSet)getAttributeInternal(YESORNOLOOKUPLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StmConfirmedCntrLovVO1.
     */
    public RowSet getStmConfirmedCntrLovVO1() {
        return (RowSet)getAttributeInternal(STMCONFIRMEDCNTRLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
