package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 16:57:25 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrMeasureHeaderTVOImpl extends CustomViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrMeasureHeaderTVOImpl() {
    }

    /**
     * Returns the variable value for bv_projectId.
     * @return variable value for bv_projectId
     */
    public Number getbv_projectId() {
        return (Number)ensureVariableManager().getVariableValue("bv_projectId");
    }

    /**
     * Sets <code>value</code> for variable bv_projectId.
     * @param value value to bind as bv_projectId
     */
    public void setbv_projectId(Number value) {
        ensureVariableManager().setVariableValue("bv_projectId", value);
    }

    /**
     * Returns the variable value for bvCntrId.
     * @return variable value for bvCntrId
     */
    public Number getbvCntrId() {
        return (Number)ensureVariableManager().getVariableValue("bvCntrId");
    }

    /**
     * Sets <code>value</code> for variable bvCntrId.
     * @param value value to bind as bvCntrId
     */
    public void setbvCntrId(Number value) {
        ensureVariableManager().setVariableValue("bvCntrId", value);
    }
    
    
    public Number getSumProductionTotal() {
       return getTotal("ProductionTotal");
    }
    
    public Number getSumOtherSubcntrOutput() {
       return getTotal("OtherSubcntrOutput");
    }
    
    public Number getSumOwerConfirmQuantity() {
       return getTotal("OwerConfirmQuantity");
    }
    
    public Number getSumCntrVisaConfirmQuantity() {
       return getTotal("CntrVisaConfirmQuantity");
    }
    
   
    
    
    
}
