package cn.com.cscec8b.bm.cntrmeasure.model.services;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 30 09:45:29 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomAppModuleDefImpl extends ApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CustomAppModuleDefImpl() {
    }
}
