package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomEntityImpl;
import cn.com.cscec8b.framework.model.common.CustomViewRowImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 03 10:20:55 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrMeasureLineTVORowImpl extends CustomViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CntrMeasureLineId {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCntrMeasureLineId();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCntrMeasureLineId((Number)value);
            }
        }
        ,
        CntrMeasureHeaderId {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCntrMeasureHeaderId();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCntrMeasureHeaderId((Number)value);
            }
        }
        ,
        LineNum {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getLineNum();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setLineNum((String)value);
            }
        }
        ,
        CntrListLineId {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCntrListLineId();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCntrListLineId((Number)value);
            }
        }
        ,
        CntrListUomCode {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCntrListUomCode();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCntrListUomCode((String)value);
            }
        }
        ,
        BudgetQuantity {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getBudgetQuantity();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setBudgetQuantity((Number)value);
            }
        }
        ,
        CumulativeQuantity {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCumulativeQuantity();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCumulativeQuantity((Number)value);
            }
        }
        ,
        CompletionPercentage {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCompletionPercentage();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCompletionPercentage((Number)value);
            }
        }
        ,
        EngineeringQuantity {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getEngineeringQuantity();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setEngineeringQuantity((Number)value);
            }
        }
        ,
        UnitPrice {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        MeasureAmount {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getMeasureAmount();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setMeasureAmount((Number)value);
            }
        }
        ,
        TaskId {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getTaskId();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setTaskId((String)value);
            }
        }
        ,
        TaskName {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getTaskName();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setTaskName((String)value);
            }
        }
        ,
        TaskNumber {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getTaskNumber();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setTaskNumber((String)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        ProductionProAmount {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getProductionProAmount();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setProductionProAmount((Number)value);
            }
        }
        ,
        CntrListHeaderId {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCntrListHeaderId();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCntrListHeaderId((Number)value);
            }
        }
        ,
        LineTaxRate {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getLineTaxRate();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setLineTaxRate((String)value);
            }
        }
        ,
        CntrListName {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCntrListName();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCntrListName((String)value);
            }
        }
        ,
        CntrListNumber {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getCntrListNumber();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setCntrListNumber((String)value);
            }
        }
        ,
        BmCntrMeasureHeaderT {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getBmCntrMeasureHeaderT();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BmCntrMeasureListLovVO1 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getBmCntrMeasureListLovVO1();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MtlUnitsOfMeasureLovVO1 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getMtlUnitsOfMeasureLovVO1();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BmCntrMeasureListHeaderLovVO1 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getBmCntrMeasureListHeaderLovVO1();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaTasksLovVO1 {
            public Object get(BmCntrMeasureLineTVORowImpl obj) {
                return obj.getPaTasksLovVO1();
            }

            public void put(BmCntrMeasureLineTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BmCntrMeasureLineTVORowImpl object);

        public abstract void put(BmCntrMeasureLineTVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CNTRMEASURELINEID = AttributesEnum.CntrMeasureLineId.index();
    public static final int CNTRMEASUREHEADERID = AttributesEnum.CntrMeasureHeaderId.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int CNTRLISTLINEID = AttributesEnum.CntrListLineId.index();
    public static final int CNTRLISTUOMCODE = AttributesEnum.CntrListUomCode.index();
    public static final int BUDGETQUANTITY = AttributesEnum.BudgetQuantity.index();
    public static final int CUMULATIVEQUANTITY = AttributesEnum.CumulativeQuantity.index();
    public static final int COMPLETIONPERCENTAGE = AttributesEnum.CompletionPercentage.index();
    public static final int ENGINEERINGQUANTITY = AttributesEnum.EngineeringQuantity.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int MEASUREAMOUNT = AttributesEnum.MeasureAmount.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TASKNAME = AttributesEnum.TaskName.index();
    public static final int TASKNUMBER = AttributesEnum.TaskNumber.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int PRODUCTIONPROAMOUNT = AttributesEnum.ProductionProAmount.index();
    public static final int CNTRLISTHEADERID = AttributesEnum.CntrListHeaderId.index();
    public static final int LINETAXRATE = AttributesEnum.LineTaxRate.index();
    public static final int CNTRLISTNAME = AttributesEnum.CntrListName.index();
    public static final int CNTRLISTNUMBER = AttributesEnum.CntrListNumber.index();
    public static final int BMCNTRMEASUREHEADERT = AttributesEnum.BmCntrMeasureHeaderT.index();
    public static final int BMCNTRMEASURELISTLOVVO1 = AttributesEnum.BmCntrMeasureListLovVO1.index();
    public static final int MTLUNITSOFMEASURELOVVO1 = AttributesEnum.MtlUnitsOfMeasureLovVO1.index();
    public static final int BMCNTRMEASURELISTHEADERLOVVO1 = AttributesEnum.BmCntrMeasureListHeaderLovVO1.index();
    public static final int PATASKSLOVVO1 = AttributesEnum.PaTasksLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrMeasureLineTVORowImpl() {
    }

    /**
     * Gets BmCntrMeasureLineTEO entity object.
     * @return the BmCntrMeasureLineTEO
     */
    public CustomEntityImpl getBmCntrMeasureLineTEO() {
        return (CustomEntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CNTR_MEASURE_LINE_ID using the alias name CntrMeasureLineId.
     * @return the CNTR_MEASURE_LINE_ID
     */
    public Number getCntrMeasureLineId() {
        return (Number) getAttributeInternal(CNTRMEASURELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_MEASURE_LINE_ID using the alias name CntrMeasureLineId.
     * @param value value to set the CNTR_MEASURE_LINE_ID
     */
    public void setCntrMeasureLineId(Number value) {
        setAttributeInternal(CNTRMEASURELINEID, value);
    }

    /**
     * Gets the attribute value for CNTR_MEASURE_HEADER_ID using the alias name CntrMeasureHeaderId.
     * @return the CNTR_MEASURE_HEADER_ID
     */
    public Number getCntrMeasureHeaderId() {
        return (Number) getAttributeInternal(CNTRMEASUREHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_MEASURE_HEADER_ID using the alias name CntrMeasureHeaderId.
     * @param value value to set the CNTR_MEASURE_HEADER_ID
     */
    public void setCntrMeasureHeaderId(Number value) {
        setAttributeInternal(CNTRMEASUREHEADERID, value);
    }

    /**
     * Gets the attribute value for LINE_NUM using the alias name LineNum.
     * @return the LINE_NUM
     */
    public String getLineNum() {
        return (String) getAttributeInternal(LINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NUM using the alias name LineNum.
     * @param value value to set the LINE_NUM
     */
    public void setLineNum(String value) {
        setAttributeInternal(LINENUM, value);
    }

    /**
     * Gets the attribute value for CNTR_LIST_LINE_ID using the alias name CntrListLineId.
     * @return the CNTR_LIST_LINE_ID
     */
    public Number getCntrListLineId() {
        return (Number) getAttributeInternal(CNTRLISTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_LIST_LINE_ID using the alias name CntrListLineId.
     * @param value value to set the CNTR_LIST_LINE_ID
     */
    public void setCntrListLineId(Number value) {
        setAttributeInternal(CNTRLISTLINEID, value);
    }

    /**
     * Gets the attribute value for CNTR_LIST_UOM_CODE using the alias name CntrListUomCode.
     * @return the CNTR_LIST_UOM_CODE
     */
    public String getCntrListUomCode() {
        return (String) getAttributeInternal(CNTRLISTUOMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CNTR_LIST_UOM_CODE using the alias name CntrListUomCode.
     * @param value value to set the CNTR_LIST_UOM_CODE
     */
    public void setCntrListUomCode(String value) {
        setAttributeInternal(CNTRLISTUOMCODE, value);
    }

    /**
     * Gets the attribute value for BUDGET_QUANTITY using the alias name BudgetQuantity.
     * @return the BUDGET_QUANTITY
     */
    public Number getBudgetQuantity() {
        return (Number) getAttributeInternal(BUDGETQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_QUANTITY using the alias name BudgetQuantity.
     * @param value value to set the BUDGET_QUANTITY
     */
    public void setBudgetQuantity(Number value) {
        setAttributeInternal(BUDGETQUANTITY, value);
    }

    /**
     * Gets the attribute value for CUMULATIVE_QUANTITY using the alias name CumulativeQuantity.
     * @return the CUMULATIVE_QUANTITY
     */
    public Number getCumulativeQuantity() {
        return (Number) getAttributeInternal(CUMULATIVEQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CUMULATIVE_QUANTITY using the alias name CumulativeQuantity.
     * @param value value to set the CUMULATIVE_QUANTITY
     */
    public void setCumulativeQuantity(Number value) {
        setAttributeInternal(CUMULATIVEQUANTITY, value);
    }

    /**
     * Gets the attribute value for COMPLETION_PERCENTAGE using the alias name CompletionPercentage.
     * @return the COMPLETION_PERCENTAGE
     */
    public Number getCompletionPercentage() {
        return (Number) getAttributeInternal(COMPLETIONPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPLETION_PERCENTAGE using the alias name CompletionPercentage.
     * @param value value to set the COMPLETION_PERCENTAGE
     */
    public void setCompletionPercentage(Number value) {
        setAttributeInternal(COMPLETIONPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for ENGINEERING_QUANTITY using the alias name EngineeringQuantity.
     * @return the ENGINEERING_QUANTITY
     */
    public Number getEngineeringQuantity() {
        return (Number) getAttributeInternal(ENGINEERINGQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ENGINEERING_QUANTITY using the alias name EngineeringQuantity.
     * @param value value to set the ENGINEERING_QUANTITY
     */
    public void setEngineeringQuantity(Number value) {
        setAttributeInternal(ENGINEERINGQUANTITY, value);
    }

    /**
     * Gets the attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @return the UNIT_PRICE
     */
    public Number getUnitPrice() {
        return (Number) getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @param value value to set the UNIT_PRICE
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for MEASURE_AMOUNT using the alias name MeasureAmount.
     * @return the MEASURE_AMOUNT
     */
    public Number getMeasureAmount() {
        return (Number) getAttributeInternal(MEASUREAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_AMOUNT using the alias name MeasureAmount.
     * @param value value to set the MEASURE_AMOUNT
     */
    public void setMeasureAmount(Number value) {
        setAttributeInternal(MEASUREAMOUNT, value);
    }

    /**
     * Gets the attribute value for TASK_ID using the alias name TaskId.
     * @return the TASK_ID
     */
    public String getTaskId() {
        return (String) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId.
     * @param value value to set the TASK_ID
     */
    public void setTaskId(String value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaskName.
     * @return the TaskName
     */
    public String getTaskName() {
        return (String) getAttributeInternal(TASKNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaskName.
     * @param value value to set the  TaskName
     */
    public void setTaskName(String value) {
        setAttributeInternal(TASKNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaskNumber.
     * @return the TaskNumber
     */
    public String getTaskNumber() {
        return (String) getAttributeInternal(TASKNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaskNumber.
     * @param value value to set the  TaskNumber
     */
    public void setTaskNumber(String value) {
        setAttributeInternal(TASKNUMBER, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrListHeaderId.
     * @return the CntrListHeaderId
     */
    public Number getCntrListHeaderId() {
        return (Number) getAttributeInternal(CNTRLISTHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListHeaderId.
     * @param value value to set the  CntrListHeaderId
     */
    public void setCntrListHeaderId(Number value) {
        setAttributeInternal(CNTRLISTHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineTaxRate.
     * @return the LineTaxRate
     */
    public String getLineTaxRate() {
        return (String) getAttributeInternal(LINETAXRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineTaxRate.
     * @param value value to set the  LineTaxRate
     */
    public void setLineTaxRate(String value) {
        setAttributeInternal(LINETAXRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrListName.
     * @return the CntrListName
     */
    public String getCntrListName() {
        return (String) getAttributeInternal(CNTRLISTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListName.
     * @param value value to set the  CntrListName
     */
    public void setCntrListName(String value) {
        setAttributeInternal(CNTRLISTNAME, value);
    }


    /**
     * Gets the attribute value for the calculated attribute CntrListNumber.
     * @return the CntrListNumber
     */
    public String getCntrListNumber() {
        return (String) getAttributeInternal(CNTRLISTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListNumber.
     * @param value value to set the  CntrListNumber
     */
    public void setCntrListNumber(String value) {
        setAttributeInternal(CNTRLISTNUMBER, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_PRO_AMOUNT using the alias name ProductionProAmount.
     * @return the PRODUCTION_PRO_AMOUNT
     */
    public Number getProductionProAmount() {
        return (Number) getAttributeInternal(PRODUCTIONPROAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_PRO_AMOUNT using the alias name ProductionProAmount.
     * @param value value to set the PRODUCTION_PRO_AMOUNT
     */
    public void setProductionProAmount(Number value) {
        setAttributeInternal(PRODUCTIONPROAMOUNT, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link BmCntrMeasureHeaderT.
     */
    public Row getBmCntrMeasureHeaderT() {
        return (Row)getAttributeInternal(BMCNTRMEASUREHEADERT);
    }

    /**
     * Sets the master-detail link BmCntrMeasureHeaderT between this object and <code>value</code>.
     */
    public void setBmCntrMeasureHeaderT(Row value) {
        setAttributeInternal(BMCNTRMEASUREHEADERT, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> BmCntrMeasureListLovVO1.
     */
    public RowSet getBmCntrMeasureListLovVO1() {
        return (RowSet)getAttributeInternal(BMCNTRMEASURELISTLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MtlUnitsOfMeasureLovVO1.
     */
    public RowSet getMtlUnitsOfMeasureLovVO1() {
        return (RowSet)getAttributeInternal(MTLUNITSOFMEASURELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BmCntrMeasureListHeaderLovVO1.
     */
    public RowSet getBmCntrMeasureListHeaderLovVO1() {
        return (RowSet)getAttributeInternal(BMCNTRMEASURELISTHEADERLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PaTasksLovVO1.
     */
    public RowSet getPaTasksLovVO1() {
        return (RowSet)getAttributeInternal(PATASKSLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
