package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomViewRowImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 25 14:49:47 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrMeasureQueryVORowImpl extends CustomViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CostAccountType {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCostAccountType();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCostAccountType((String)value);
            }
        }
        ,
        FirstLevelAccount {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getFirstLevelAccount();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setFirstLevelAccount((Number)value);
            }
        }
        ,
        SecondLevelAccount {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getSecondLevelAccount();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setSecondLevelAccount((Number)value);
            }
        }
        ,
        UnitPrice {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        EngineeringQuantity {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getEngineeringQuantity();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setEngineeringQuantity((Number)value);
            }
        }
        ,
        MeasureAmount {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getMeasureAmount();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setMeasureAmount((Number)value);
            }
        }
        ,
        CntrListUomCode {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrListUomCode();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrListUomCode((String)value);
            }
        }
        ,
        MeasureStartDate {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getMeasureStartDate();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setMeasureStartDate((Date)value);
            }
        }
        ,
        CntrListName {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrListName();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrListName((String)value);
            }
        }
        ,
        ContactName {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getContactName();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setContactName((String)value);
            }
        }
        ,
        MeasureEndDate {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getMeasureEndDate();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setMeasureEndDate((Date)value);
            }
        }
        ,
        ListName {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getListName();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setListName((String)value);
            }
        }
        ,
        ProjectId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setProjectId((Number)value);
            }
        }
        ,
        ProjectNumber {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getProjectNumber();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setProjectNumber((String)value);
            }
        }
        ,
        CntrId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrId((Number)value);
            }
        }
        ,
        ContactNumber {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getContactNumber();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setContactNumber((String)value);
            }
        }
        ,
        ProjectName {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getProjectName();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setProjectName((String)value);
            }
        }
        ,
        CustomerId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        CustomerName {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        CntrListHeaderId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrListHeaderId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrListHeaderId((Number)value);
            }
        }
        ,
        CntrListLineId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrListLineId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrListLineId((Number)value);
            }
        }
        ,
        CntrMeasureHeaderId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrMeasureHeaderId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrMeasureHeaderId((Number)value);
            }
        }
        ,
        CntrMeasureLineId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrMeasureLineId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrMeasureLineId((Number)value);
            }
        }
        ,
        LineNum {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getLineNum();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setLineNum((String)value);
            }
        }
        ,
        TaskId {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getTaskId();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setTaskId((String)value);
            }
        }
        ,
        TaskName {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getTaskName();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setTaskName((String)value);
            }
        }
        ,
        TaskNumber {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getTaskNumber();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setTaskNumber((String)value);
            }
        }
        ,
        DocumentNumber {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getDocumentNumber();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setDocumentNumber((String)value);
            }
        }
        ,
        Description {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        CntrListNumber {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCntrListNumber();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCntrListNumber((String)value);
            }
        }
        ,
        CurrentMeasureAmount {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCurrentMeasureAmount();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setCurrentMeasureAmount((Number)value);
            }
        }
        ,
        MtlUnitsOfMeasureLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getMtlUnitsOfMeasureLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaTasksLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getPaTasksLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BmCntrMeasureListHeaderLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getBmCntrMeasureListHeaderLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FirstCostAccountLineLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getFirstCostAccountLineLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SecondCostAccountLineLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getSecondCostAccountLineLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CostAccountHeaderLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getCostAccountHeaderLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmCustomersAndSitsLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getStmCustomersAndSitsLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmConfirmedCntrLovVO1 {
            public Object get(BmCntrMeasureQueryVORowImpl obj) {
                return obj.getStmConfirmedCntrLovVO1();
            }

            public void put(BmCntrMeasureQueryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BmCntrMeasureQueryVORowImpl object);

        public abstract void put(BmCntrMeasureQueryVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COSTACCOUNTTYPE = AttributesEnum.CostAccountType.index();
    public static final int FIRSTLEVELACCOUNT = AttributesEnum.FirstLevelAccount.index();
    public static final int SECONDLEVELACCOUNT = AttributesEnum.SecondLevelAccount.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int ENGINEERINGQUANTITY = AttributesEnum.EngineeringQuantity.index();
    public static final int MEASUREAMOUNT = AttributesEnum.MeasureAmount.index();
    public static final int CNTRLISTUOMCODE = AttributesEnum.CntrListUomCode.index();
    public static final int MEASURESTARTDATE = AttributesEnum.MeasureStartDate.index();
    public static final int CNTRLISTNAME = AttributesEnum.CntrListName.index();
    public static final int CONTACTNAME = AttributesEnum.ContactName.index();
    public static final int MEASUREENDDATE = AttributesEnum.MeasureEndDate.index();
    public static final int LISTNAME = AttributesEnum.ListName.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int PROJECTNUMBER = AttributesEnum.ProjectNumber.index();
    public static final int CNTRID = AttributesEnum.CntrId.index();
    public static final int CONTACTNUMBER = AttributesEnum.ContactNumber.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CNTRLISTHEADERID = AttributesEnum.CntrListHeaderId.index();
    public static final int CNTRLISTLINEID = AttributesEnum.CntrListLineId.index();
    public static final int CNTRMEASUREHEADERID = AttributesEnum.CntrMeasureHeaderId.index();
    public static final int CNTRMEASURELINEID = AttributesEnum.CntrMeasureLineId.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TASKNAME = AttributesEnum.TaskName.index();
    public static final int TASKNUMBER = AttributesEnum.TaskNumber.index();
    public static final int DOCUMENTNUMBER = AttributesEnum.DocumentNumber.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int CNTRLISTNUMBER = AttributesEnum.CntrListNumber.index();
    public static final int CURRENTMEASUREAMOUNT = AttributesEnum.CurrentMeasureAmount.index();
    public static final int MTLUNITSOFMEASURELOVVO1 = AttributesEnum.MtlUnitsOfMeasureLovVO1.index();
    public static final int PATASKSLOVVO1 = AttributesEnum.PaTasksLovVO1.index();
    public static final int BMCNTRMEASURELISTHEADERLOVVO1 = AttributesEnum.BmCntrMeasureListHeaderLovVO1.index();
    public static final int FIRSTCOSTACCOUNTLINELOVVO1 = AttributesEnum.FirstCostAccountLineLovVO1.index();
    public static final int SECONDCOSTACCOUNTLINELOVVO1 = AttributesEnum.SecondCostAccountLineLovVO1.index();
    public static final int COSTACCOUNTHEADERLOVVO1 = AttributesEnum.CostAccountHeaderLovVO1.index();
    public static final int STMCUSTOMERSANDSITSLOVVO1 = AttributesEnum.StmCustomersAndSitsLovVO1.index();
    public static final int STMCONFIRMEDCNTRLOVVO1 = AttributesEnum.StmConfirmedCntrLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrMeasureQueryVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectId.
     * @return the ProjectId
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectId.
     * @param value value to set the  ProjectId
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectNumber.
     * @return the ProjectNumber
     */
    public String getProjectNumber() {
        return (String) getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectNumber.
     * @param value value to set the  ProjectNumber
     */
    public void setProjectNumber(String value) {
        setAttributeInternal(PROJECTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeasureStartDate.
     * @return the MeasureStartDate
     */
    public Date getMeasureStartDate() {
        return (Date) getAttributeInternal(MEASURESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeasureStartDate.
     * @param value value to set the  MeasureStartDate
     */
    public void setMeasureStartDate(Date value) {
        setAttributeInternal(MEASURESTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrId.
     * @return the CntrId
     */
    public Number getCntrId() {
        return (Number) getAttributeInternal(CNTRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrId.
     * @param value value to set the  CntrId
     */
    public void setCntrId(Number value) {
        setAttributeInternal(CNTRID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContactNumber.
     * @return the ContactNumber
     */
    public String getContactNumber() {
        return (String) getAttributeInternal(CONTACTNUMBER);
    }
    



    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContactNumber.
     * @param value value to set the  ContactNumber
     */
    public void setContactNumber(String value) {
        setAttributeInternal(CONTACTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrListNumber.
     * @return the CntrListNumber
     */
    public String getCntrListNumber() {
        return (String) getAttributeInternal(CNTRLISTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListNumber.
     * @param value value to set the  CntrListNumber
     */
    public void setCntrListNumber(String value) {
        setAttributeInternal(CNTRLISTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ListName.
     * @return the ListName
     */
    public String getListName() {
        return (String) getAttributeInternal(LISTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ListName.
     * @param value value to set the  ListName
     */
    public void setListName(String value) {
        setAttributeInternal(LISTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectName.
     * @return the ProjectName
     */
    public String getProjectName() {
        return (String) getAttributeInternal(PROJECTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectName.
     * @param value value to set the  ProjectName
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeasureEndDate.
     * @return the MeasureEndDate
     */
    public Date getMeasureEndDate() {
        return (Date) getAttributeInternal(MEASUREENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeasureEndDate.
     * @param value value to set the  MeasureEndDate
     */
    public void setMeasureEndDate(Date value) {
        setAttributeInternal(MEASUREENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContactName.
     * @return the ContactName
     */
    public String getContactName() {
        return (String) getAttributeInternal(CONTACTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContactName.
     * @param value value to set the  ContactName
     */
    public void setContactName(String value) {
        setAttributeInternal(CONTACTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrListHeaderId.
     * @return the CntrListHeaderId
     */
    public Number getCntrListHeaderId() {
        return (Number) getAttributeInternal(CNTRLISTHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListHeaderId.
     * @param value value to set the  CntrListHeaderId
     */
    public void setCntrListHeaderId(Number value) {
        setAttributeInternal(CNTRLISTHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrListLineId.
     * @return the CntrListLineId
     */
    public Number getCntrListLineId() {
        return (Number) getAttributeInternal(CNTRLISTLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListLineId.
     * @param value value to set the  CntrListLineId
     */
    public void setCntrListLineId(Number value) {
        setAttributeInternal(CNTRLISTLINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrMeasureHeaderId.
     * @return the CntrMeasureHeaderId
     */
    public Number getCntrMeasureHeaderId() {
        return (Number) getAttributeInternal(CNTRMEASUREHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrMeasureHeaderId.
     * @param value value to set the  CntrMeasureHeaderId
     */
    public void setCntrMeasureHeaderId(Number value) {
        setAttributeInternal(CNTRMEASUREHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrListName.
     * @return the CntrListName
     */
    public String getCntrListName() {
        return (String) getAttributeInternal(CNTRLISTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListName.
     * @param value value to set the  CntrListName
     */
    public void setCntrListName(String value) {
        setAttributeInternal(CNTRLISTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FirstLevelAccount.
     * @return the FirstLevelAccount
     */
    public Number getFirstLevelAccount() {
        return (Number) getAttributeInternal(FIRSTLEVELACCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FirstLevelAccount.
     * @param value value to set the  FirstLevelAccount
     */
    public void setFirstLevelAccount(Number value) {
        setAttributeInternal(FIRSTLEVELACCOUNT, value);
    }


    /**
     * Gets the attribute value for the calculated attribute SecondLevelAccount.
     * @return the SecondLevelAccount
     */
    public Number getSecondLevelAccount() {
        return (Number) getAttributeInternal(SECONDLEVELACCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SecondLevelAccount.
     * @param value value to set the  SecondLevelAccount
     */
    public void setSecondLevelAccount(Number value) {
        setAttributeInternal(SECONDLEVELACCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerId.
     * @param value value to set the  CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrMeasureLineId.
     * @return the CntrMeasureLineId
     */
    public Number getCntrMeasureLineId() {
        return (Number) getAttributeInternal(CNTRMEASURELINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrMeasureLineId.
     * @param value value to set the  CntrMeasureLineId
     */
    public void setCntrMeasureLineId(Number value) {
        setAttributeInternal(CNTRMEASURELINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineNum.
     * @return the LineNum
     */
    public String getLineNum() {
        return (String) getAttributeInternal(LINENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineNum.
     * @param value value to set the  LineNum
     */
    public void setLineNum(String value) {
        setAttributeInternal(LINENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrListUomCode.
     * @return the CntrListUomCode
     */
    public String getCntrListUomCode() {
        return (String) getAttributeInternal(CNTRLISTUOMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrListUomCode.
     * @param value value to set the  CntrListUomCode
     */
    public void setCntrListUomCode(String value) {
        setAttributeInternal(CNTRLISTUOMCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EngineeringQuantity.
     * @return the EngineeringQuantity
     */
    public Number getEngineeringQuantity() {
        return (Number) getAttributeInternal(ENGINEERINGQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EngineeringQuantity.
     * @param value value to set the  EngineeringQuantity
     */
    public void setEngineeringQuantity(Number value) {
        setAttributeInternal(ENGINEERINGQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitPrice.
     * @return the UnitPrice
     */
    public Number getUnitPrice() {
        return (Number) getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitPrice.
     * @param value value to set the  UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeasureAmount
     * @return the getAllMeasureAmount
     */
    public Number getMeasureAmount() {
     return (Number) getAttributeInternal(MEASUREAMOUNT);
    }
    

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeasureAmount.
     * @param value value to set the  MeasureAmount
     */
    public void setMeasureAmount(Number value) {
        setAttributeInternal(MEASUREAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentMeasureAmount.
     * @return the CurrentMeasureAmount
     */
    public Number getCurrentMeasureAmount() {
       // return (Number) getAttributeInternal(CURRENTMEASUREAMOUNT);
       return ((BmCntrMeasureQueryVOImpl)getViewObject()).getCurrentMeasureAmount();

    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentMeasureAmount.
     * @param value value to set the  CurrentMeasureAmount
     */
    public void setCurrentMeasureAmount(Number value) {
        setAttributeInternal(CURRENTMEASUREAMOUNT, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TaskId.
     * @return the TaskId
     */
    public String getTaskId() {
        return (String) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaskId.
     * @param value value to set the  TaskId
     */
    public void setTaskId(String value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaskName.
     * @return the TaskName
     */
    public String getTaskName() {
        return (String) getAttributeInternal(TASKNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaskName.
     * @param value value to set the  TaskName
     */
    public void setTaskName(String value) {
        setAttributeInternal(TASKNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaskNumber.
     * @return the TaskNumber
     */
    public String getTaskNumber() {
        return (String) getAttributeInternal(TASKNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaskNumber.
     * @param value value to set the  TaskNumber
     */
    public void setTaskNumber(String value) {
        setAttributeInternal(TASKNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocumentNumber.
     * @return the DocumentNumber
     */
    public String getDocumentNumber() {
        return (String) getAttributeInternal(DOCUMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocumentNumber.
     * @param value value to set the  DocumentNumber
     */
    public void setDocumentNumber(String value) {
        setAttributeInternal(DOCUMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CostAccountType.
     * @return the CostAccountType
     */
    public String getCostAccountType() {
        return (String) getAttributeInternal(COSTACCOUNTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CostAccountType.
     * @param value value to set the  CostAccountType
     */
    public void setCostAccountType(String value) {
        setAttributeInternal(COSTACCOUNTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MtlUnitsOfMeasureLovVO1.
     */
    public RowSet getMtlUnitsOfMeasureLovVO1() {
        return (RowSet)getAttributeInternal(MTLUNITSOFMEASURELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PaTasksLovVO1.
     */
    public RowSet getPaTasksLovVO1() {
        return (RowSet)getAttributeInternal(PATASKSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BmCntrMeasureListHeaderLovVO1.
     */
    public RowSet getBmCntrMeasureListHeaderLovVO1() {
        return (RowSet)getAttributeInternal(BMCNTRMEASURELISTHEADERLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FirstCostAccountLineLovVO1.
     */
    public RowSet getFirstCostAccountLineLovVO1() {
        return (RowSet)getAttributeInternal(FIRSTCOSTACCOUNTLINELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SecondCostAccountLineLovVO1.
     */
    public RowSet getSecondCostAccountLineLovVO1() {
        return (RowSet)getAttributeInternal(SECONDCOSTACCOUNTLINELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CostAccountHeaderLovVO1.
     */
    public RowSet getCostAccountHeaderLovVO1() {
        return (RowSet)getAttributeInternal(COSTACCOUNTHEADERLOVVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> StmCustomersAndSitsLovVO1.
     */
    public RowSet getStmCustomersAndSitsLovVO1() {
        return (RowSet)getAttributeInternal(STMCUSTOMERSANDSITSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StmConfirmedCntrLovVO1.
     */
    public RowSet getStmConfirmedCntrLovVO1() {
        return (RowSet)getAttributeInternal(STMCONFIRMEDCNTRLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
