package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 28 17:48:26 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrVerifyHeaderTVOImpl extends CustomViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrVerifyHeaderTVOImpl() {
    }


    public Number getCurrentOwnerConfirmQuantities() {
        return getTotal("OwerConfirmQuantity");
    }

    public Number getCurrentOtherSubCntrOutput() {
        return getTotal("OtherSubcntrOutput");
    }

    public Number getCurrentActualOutput() {
        return getTotal("ActualOutput");
    }

    public Number getCurrentProSubcntrOutput() {
        return getTotal("ProSubcntrOutput");
    }

    public Number getCurrentLaborAmount() {
        return getTotal("LaborAmount");
    }

    public Number getCurrentCntrPaymentAmount() {
        return getTotal("CntrPaymentAmount");
    }

    public Number getCurrentSecurityAmount() {
        return getTotal("SecurityAmount");
    }

    public Number getCurrentActualPaymentAmount() {
        return getTotal("ActualPaymentAmount");
    }

    public Number getCurrentLeftConfirmAmount() {
        return getTotal("LeftConfirmAmount");
    }

    public Number getCurrentAlreadyConfirmAmount() {
        return getTotal("AlreadyConfirmAmount");
    }
//CntrVisaConfirmQuantity
        public Number getCurrentVisaConfirmQuantity() {
        return getTotal("CntrVisaConfirmQuantity");
    }
    /**
     * Returns the variable value for bv_projectId.
     * @return variable value for bv_projectId
     */
    public Number getbv_projectId() {
        return (Number)ensureVariableManager().getVariableValue("bv_projectId");
    }

    /**
     * Sets <code>value</code> for variable bv_projectId.
     * @param value value to bind as bv_projectId
     */
    public void setbv_projectId(Number value) {
        ensureVariableManager().setVariableValue("bv_projectId", value);
    }
}
