package cn.com.cscec8b.bm.cntrmeasure.model.queries;

import cn.com.cscec8b.framework.model.common.CustomViewObjectImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.SQLBuilder;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 14:41:57 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmCntrConfirmVOImpl extends CustomViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BmCntrConfirmVOImpl() {
    }
   
   
    public Number getCurrentLeftConfirmAmount() {
         return getTotal("LeftConfirmAmount");
      }
    public Number getCurrentAlreadyConfirmAmount() {
         return getTotal("AlreadyConfirmAmount");
    }
    public Number getCurrentAllTransferAmount() {
         return getTotal("CurrentTransferAmount");
      }
    public Number getCurrentOwerConfirmQuantity() {
         return getTotal("OwerConfirmQuantity");
    }

    /**
     * Returns the variable value for bvProjectId.
     * @return variable value for bvProjectId
     */
    public Number getbvProjectId() {
        return (Number)ensureVariableManager().getVariableValue("bvProjectId");
    }

    /**
     * Sets <code>value</code> for variable bvProjectId.
     * @param value value to bind as bvProjectId
     */
    public void setbvProjectId(Number value) {
        ensureVariableManager().setVariableValue("bvProjectId", value);
    }
}
